name: Bartosz CI/CD pipeline

on:
    push:
      branches:
        - main
    pull_request:
    workflow_dispatch:

jobs:
  run-the-tests:

    runs-on: macos-latest

    strategy:
      matrix:
        python-version: ["3.12", "3.13","3.14"]

    permissions:
      checks: write
      pull-requests: write

    steps:        
      - name: Checkout latest code from GitHub
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}
        
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: pytest --junit-xml=test-results.xml ./tests/account_tests.py
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        if: (!cancelled())
        with:
          files:  |
            *test-results.xml
            